<?php

use dawfony\Ti;

global $URL_PATH;
?>

<?php Ti::extend("view/MainView.phtml"); ?>

<?php Ti::startBlock("content"); ?>


<div class="container">
    <div id="paramVacios">
    <form class="mt-4" id="form"  autocomplete="off" action="<?=$URL_PATH?>/registro" onsubmit="return validarformulario()" method='POST'>
        <div class="form-group row">
            <label for="login" class="col-md-2 col-form-label">Login</label>
            <div class="col-sm-10">
                <input type="text"  class="form-control" id="login"  onchange="comprobarlogin()" value="<?=$usuario->login?>" name="login" required>
                <span id="loginExistente"></span>
            </div>
        </div>
        <div class="form-group row">
            <label for="pass1" class="col-md-2 col-form-label">Contraseña: </label>
            <div class="col-sm-10">
                <input type="password" class="form-control" id="pass1" name="password" required>
                <span id="errPass1"></span>
            </div>
        </div>
        <div class="form-group row">
            <label for="pass2" class="col-md-2 col-form-label">Repite: </label>
            <div class="col-sm-10">
                <input type="password" class="form-control" id="pass2" name="pass2" required>
                <span id="errPass2"></span>
            </div>
        </div>
        <div class="form-group row">
            <label for="nombre" class="col-md-2 col-form-label">Nombre</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="nombre" name="nombre" value="<?=$usuario->nombre?>">
                <span id="errNombre"></span>
            </div>
        </div>
        <div class="form-group row">
            <label for="email" class="col-md-2 col-form-label">Email</label>
            <div class="col-sm-10">
                <input type="email" class="form-control" id="email" name="email" value="<?=$usuario->email?>">
                <span id="errEmail"></span>
            </div>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary offset-md-2">Enviar</button>
        </div>
    </form>
    </div>
</div>
<?php Ti::endBlock(); ?>
<?php Ti::endExtend(); ?>