<?php

use dawfony\Ti;

global $URL_PATH;
?>

<?php Ti::extend("view/mainView.phtml") ?>
<?php Ti::startBlock("content"); ?>


<div class="row m-2">
    <div class="col-5">
        <img class="img-fluid rounded" src="<?= $URL_PATH ?>/assets/fotos/<?= $post->foto ?>" alt="postFoto:<?= $post->resumen ?>">
    </div>

    <div class="col-7">
        <h4><?= $post->resumen ?></h4>
        <p><?= $post->texto ?></p>
        <!-- Aqui va todo el tema de comentario y like's -->
        <?php if (isset($_SESSION["login"])) : ?>
            <a style="color:gray" href="javascript:void(0)" onclick="likeClick(<?= $post->id ?>)">
            <?php endif ?>
            <?php /* El atributo id del elemento del corazón tiene como sufijo el id del post */ ?>
            <i id="likecorazon<?= $post->id ?>" class="fa fa-heart<?= ($post->like ? " text-danger" : "") ?>"></i>
            <?php if (isset($_SESSION["login"])) : ?>
            </a>
        <?php endif ?>
        <?php /* Lo mismo para el elemento que contiene la cuenta de likes:
                             su atributo id contiene como sufijo el id del post */ ?>
        <span id="likecontador<?= $post->id ?>">
            <?= $post->numLikes ?>
        </span>
        <a  style="color:green" href="#comentarios"><i class="fa fa-comments"></i><?= $post->numComentarios ?></a>
        <div>
            Por <a style="color:red" href="<?= $URL_PATH ?>/perfil/<?= $post->usuario_login ?>"><?= $post->usuario_login ?></a>
                en <em><?= $post->categoria_post_id ?></em>
                el <?= $post->fecha ?>
        </div>
    </div>
</div>
<hr>
<h4 id="comentarios">Comentarios:</h4>
<?php if (isset($_SESSION["login"])) : ?>
    <?php $placeholder = ($post->numComentarios == 0 ? "Sé el primero en comentar" : "Escribe aquí tu comentario") ?>
    <form method="POST" action="<?= $URL_PATH ?>/leerMas/<?= $post->id ?>/comentario/new">
        <div class="form-group row">
            <div class="col-sm-8">
                <textarea placeholder="<?= $placeholder ?>" class="form-control" rows="2" name="texto" id="texto"></textarea>
            </div>
            <div class="col-sm-4">
                <button type="submit" class="btn btn-success">Comentar</button>
            </div>
        </div>
    </form>
<?php else : ?>
    <div class="alert alert-info">
        Inicia sesión para <?= $post->numComentarios == 0 ? "ser el primero en comentar." : "dejar tu comentario"?>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<?php endif ?>
<?php foreach ($post->comentarios as $comentario) : ?>
    <div class="row border-top border-rounded">
        <div class="col-sm-8">
            <?= $comentario->texto ?>
        </div>
        <col-sm-4>
            Por <a href="<?= $URL_PATH ?>/perfil/<?= $post->usuario_login ?>"><?= $comentario->usuario_login ?></a> el <?= $comentario->fecha ?>
        </col-sm-4>
    </div>
<?php endforeach; ?>
<script src="<?= $URL_PATH ?>/js/like.js"></script>

<!-- Falta poner los comentarios y todos los comentarios que tenga ese post -->

<?php Ti::endBlock(); ?>
<?php Ti::endExtend(); ?>