<?php

use dawfony\Ti;
global $URL_PATH;
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="<?= $URL_PATH ?>/vendor/twbs/bootstrap/dist/css/bootstrap.css">
    <script src="<?= $URL_PATH ?>/vendor/twbs/bootstrap/dist/js/bootstrap.js"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
   

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
   
    
    <script>
        var URL_PATH="<?= $URL_PATH ?>"; // Pasamos el URL_PATH de php a Javascript.
    </script>
    <script>
        var error = false;
    </script>    
    <script src="<?=$URL_PATH?>/js/main.js"></script>
    <script src="<?=$URL_PATH?>/js/borrar.js"></script>
    <script src="<?=$URL_PATH?>/js/borrarPerfil.js"></script>
    <script src="<?=$URL_PATH?>/js/validar.js"></script>
    <script src="<?=$URL_PATH?>/js/comprobarlogin.js"></script>
    
    <?php Ti::startBlock("extrahead"); ?>
    <?php Ti::endBlock() ?>
    <title>
        <?php Ti::startBlock("title"); ?>
        <?= $data["title"] ?> SocialDaw
        <?php Ti::endBlock() ?>
    </title>
</head>

<body class="container">
    <div class="jumbotron shadow" id="mainjumbo">
        <div class="text-center myfont">
        <img  class="img-fluid w-10" src="<?=$URL_PATH?>/assets/fotos/logo.png" width="400px" height="250px" alt="socialdaw logo">
        <br>
        <h3><em>Tu red de anime,jpop y kpop.</em></h3>
        </div>
    </div>
              
    <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-light bg-light">
        <a class="navbar-brand" href="<?=$URL_PATH?>/">Lo último</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <?php  if(isset($_SESSION["login"])): ?>
        
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="<?=$URL_PATH?>/perfil/<?=$_SESSION["login"]?>">Perfil</a>
                <a class="nav-item nav-link" href="<?=$URL_PATH?>/siguiendo">Siguiendo</a>
                <a class="nav-item nav-link" href="javascript:void(0)" onclick="confirmarLogout()">Cerrar Sesion</a>
            </div>
        </div>
        <?php else: ?>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="<?=$URL_PATH?>/registro">Regístrate</a>
                <a class="nav-item nav-link" href="<?=$URL_PATH?>/login">Login</a>
            </div>
        </div>
        <?php endif; ?>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Buscar" aria-label="Search">
            <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Enviar</button>
</form>
    </nav>
    <div>
        <?php Ti::startBlock("content"); ?>
        <?php Ti::endBlock() ?>
    </div>
    <footer class="rounded p-4 mt-2 text-center bg-light myfont">
       <?=date("Y")?> &copy; SocialDaw 
    </footer>
</body>

</html>