<?php

use dawfony\Ti;

global $URL_PATH;
?>

<?php Ti::extend("view/MainView.phtml"); ?>

<?php Ti::startBlock("content"); ?>


<p>Lo último:</p>
<?php foreach ($posts as $post) : ?>
    <div class="row border border-secondary rounded ml-0 mr-0 mt-1">
        <div class="col-sm-4 p-1">
            <img class="img-fluid rounded" src="<?= $URL_PATH ?>/assets/fotos/<?= $post->foto ?>" alt="Imagen: <?= $post->resumen ?>">
        </div>
        <div class="col-sm-5">
            <h4><?= $post->resumen ?></h4>
            <div class="row">
                <div class="col-sm-6"><a href="<?= $URL_PATH ?>/leerMas/<?= $post->id ?>" class="btn btn-outline-success btn-sm">Leer más</a></div>

                <div class="offset-sm-1 col-sm-5 mb-3">
                    <?php /*Pasamos el id del post al evento de javascript. Enlace solo si usuario logueado*/ ?>
                    <?php if (isset($_SESSION["login"])) : ?>
                        <a style="color:gray;" href="javascript:void(0)" onclick="likeClick(<?= $post->id ?>)">
                        <?php endif ?>
                        <?php /* El atributo id del elemento del corazón tiene como sufijo el id del post */ ?>
                        <i id="likecorazon<?= $post->id ?>" class="fa fa-heart<?= ($post->like ? " text-danger" : "") ?>"></i>
                        <?php if (isset($_SESSION["login"])) : ?>
                        </a>
                    <?php endif ?>
                    <?php /* Lo mismo para el elemento que contiene la cuenta de likes:
                             su atributo id contiene como sufijo el id del post */ ?>
                    <span id="likecontador<?= $post->id ?>">
                        <?= $post->numLikes ?>
                    </span>
                    <a style="color:green;" href="<?= $URL_PATH ?>/leerMas/<?= $post->id ?>#comentarios"><i class="fa fa-comments"></i></a> <?= $post->numComentarios ?>
                    <?php if (isset($_SESSION["rol_id"]) && $_SESSION["rol_id"] == 0) : ?>
                        <a style="color:red;" href="javascript:void(0)" onclick="borrarPost(<?= $post->id ?>)">
                        <i id="borrar<?= $post->id ?>" class="fa fa-trash"></i>
                        </a>
                        <?php endif ?>
                  </div>
            </div>
        </div>
        <div class="col-sm-3 ">
            <h5>
                Por
                 <a style="color:red;" href="<?= $URL_PATH ?>/perfil/<?= $post->usuario_login ?>"><?= $post->usuario_login ?></a>
                <img class="img-fluid rounded" src="https://avatars.dicebear.com/v2/bottts/<?= $post->usuario_login ?>.svg?options[width]=32&options[height]=32" alt="avatar: <?= $post->usuario_login ?>">
            </h5>
            <h5>en <?= $post->categoria ?></h5>
            <h6>el <?= $post->fecha ?></h6>
        </div>
    </div>
<?php endforeach; ?>
  
<!-- //paginacion como sportpedia -->


<nav aria-label="...">
  <ul class="pagination">
    <li class="page-item <?=($pagina  <= 1 ? "disabled" : "")?>">
      <a class="page-link" href="<?=$ruta .($pagina -1)?>" tabindex="-1" aria-disabled="true">Anterior</a>
    </li>
    <?php
    for($i = 1; $i <= $numpaginas; $i++){
      ?>

    <li class="page-item " >
        <a class="page-link" href="<?=$ruta?><?=$i?>"><?=$i?></a>
    </li>

      <?php
    }
    ?>
    <li class="page-item <?=($pagina + 1 > $numpaginas ? "disabled" : "")?>">
      <a class="page-link" href="<?=$ruta .($pagina + 1)?>" aria-disabled="true">Siguiente</a>
    </li>
  </ul>
</nav>



  <?php
  if (isset($_SESSION["rol_id"])) {
    require "view/botoninsertar.phtml";
  }
  ?>
  <script src="<?= $URL_PATH ?>/js/like.js"></script>
  <!-- aquí va el botoninsertar.phtml -->

  <?php Ti::endBlock(); ?>
  <?php Ti::endExtend(); ?>